### ISSUE TITLE
Accuracy on metatest_tasks_distribution

### ISSUE THREAD

**Issue by kgarg8** [spiglerg/pyMeta#1]
Hi Spigler,

Really appreciate your efforts in giving the implementation of many meta-learning algorithms.
I have one quick question about the file example_metatrain.py:

You have given the code only for training and validation. How are you calculating the accuracy of metatest_tasks_distribution?

**Comment by spiglerg** [comment]
Hi Krishna,

I have separate scripts to perform the evaluation of the meta-learners, as I needed more extensive analyses.
The meta-test accuracy can be computed by adapting the validation code in example_metatrain.py ("## META-TESTING every `test_every_k_iterations' iterations
        if outer_iter % FLAGS.test_every_k_iterations == 0:" and following block) replacing metaval_task_distribution with the metatest_task_distribution.

You may also want to parameterize the test to choose how many random meta-tasks you want to sample for your evaluation.

**Comment by kgarg8** [comment]
Thanks Spigler,
It makes sense to me to create scripts like validation code.
However, if possible, please check in those files to the repo.

**Comment by spiglerg** [comment]
I agree it would be a useful addition to the repository, and I will try to upload something soon. :)
Thank you very much for your feedback!
